version: '3'

networks:
  widget:
    name: widget-network
    driver: bridge

services:
  todos.web:
    build:
      context: .
      args:
        - NODE_ENV=production
        - PUBLIC_URL=/w/todos
    image: todos.web:local
    container_name: todos.web
    restart: unless-stopped
    environment:
      - TODOS_SERVICE_ENDPOINT=http://frontend.jahiduls.local/api/todos
      - NODE_ENV=production
    networks:
      - widget
    expose:
      - 80
