version: '3'

networks:
    default:
        external:
            name: home_network

services:
    todos:
        build: .
        image: todos.service:local
        container_name: todos
        ports:
            - 8080:80
