version: '3'

networks:
  backend:
    name: backend-network
    driver: bridge

services:
  todos:
    build: .
    image: todos.service:local
    container_name: todos.service
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - server.port=80
      - spring.profiles.active=prod
      - db.host=mongodb
      - db.user=todos
      - db.password=todos
      - db.name=todos
    networks:
      - backend
