apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo.service
  labels:
    app: todos.service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos.service
  template:
    metadata:
      labels:
        app: todos.service
    spec:
      containers:
      - name: todos-service
        image: todos.service:local
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: todos-service
spec:
  selector:
    app: todos.service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
