name: client

on:
  push:
    branches:
      - main
    paths:
      - client/**
  pull_request:
    branches:
      - main
    paths:
      - client/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
        working-directory: client
      - run: pnpm install --frozen-lockfile
        working-directory: client
      - run: pnpm run build --if-present
        working-directory: client
      - run: pnpm test
        working-directory: client
