name: service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.16
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "16"
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: service
